import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import PrelineScript from "@/components/preline/PrelineScript";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Regenera",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-light-background-100 py-8 md:bg-light-background-200 md:py-16`}
      >
        <Providers>{children}</Providers>
      </body>
      <PrelineScript />
    </html>
  );
}
