import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import PrelineScript from "@/components/preline/PrelineScript";
import Footer from "@/components/navigations/Footer";
import Providers from "@/components/Providers";
import Header from "@/components/navigations/Header";
import Sidebar from "@/components/navigations/sidebar/Sidebar";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Regenera",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} w-full h-dvh overflow-y-hidden bg-light-background-100 flex flex-col items-center`}
      >
        <Providers>
          <NextTopLoader color="#c1ffff" height={2} />
          <Header />
          <div
            className={
              "w-full h-full flex overflow-y-hidden mt-[60px] md:mt-[69.6px] "
            }
          >
            <Sidebar />
            {children}
          </div>
        </Providers>
      </body>
      <PrelineScript />
    </html>
  );
}
