import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import PrelineScript from "@/components/preline/PrelineScript";
import Footer from "@/components/navigations/Footer";
import Navbar from "@/components/navigations/navbar/Navbar";
import ReactQueryProvider from "@/components/react-query/ReactQueryProvider";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/lib/next-auth/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Regenera",
  description: "Generated by create next app",
};

export default async function GeneralLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${inter.className} w-full min-h-screen bg-light-background-100 flex flex-col items-center`}
      >
        <SessionProvider session={session}>
          <ReactQueryProvider>
            <Navbar pill={true} />
            {children}
            <Footer />
          </ReactQueryProvider>
        </SessionProvider>
      </body>
      <PrelineScript />
    </html>
  );
}
